platform :ios, '9.0'
use_frameworks!

target 'GiphyApp' do
    pod 'SwiftyJSON'
    pod 'Gifu'
    pod 'Nuke', '~> 5.0'
    pod 'Nuke-Gifu-Plugin'
    pod 'Alamofire', '~> 4.4'
    pod 'Nuke-Alamofire-Plugin'
end

